name: build

on:
  push:
    branches: [ "2.0" ]
  pull_request:
    branches: [ "2.0" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pypoetry/virtualenvs
          - os: macos-latest
            path: ~/Library/Caches/pypoetry/virtualenvs
          - os: windows-latest
            path: ~\AppData\Local\pypoetry\Cache\virtualenvs

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        run: pip install poetry

      - name: Cache poetry
        uses: actions/cache@v2
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: poetry install

      - name: Run tests with coverage
        run: poetry run pytest

#      - name: Run pylint
#        run: poetry run pylint symphony tests
#
#      - name: GitHub Action for pylint
#        if: matrix.os == 'ubuntu-latest'
#        uses: cclauss/GitHub-Action-for-pylint@0.7.0
#        with:
#          args: pip install poetry | poetry run pylint symphony tests
#      - name: pylint-and-format
#        if: matrix.os == 'ubuntu-latest'
#        uses: itsvinayak/pylint-and-format@v1.1
#      - name: Run pylint
#        if: matrix.os == 'ubuntu-latest'
#        uses: abatilo/actions-poetry@v1.1.0
#        with:
#          python_version: 3.8
#          poetry_version: 1.0.3
#          working_directory: $GITHUB_WORKSPACE/opt/
#          args: run pylint --rcfile pyproject.toml scopeserver
#      - name: Pylint run
#        if: matrix.os == 'ubuntu-latest'
#        uses: ricardochaves/python-lint@v1.3.0
#        with:
#          use-pylint: true
#          use-pycodestyle: false
#          use-flake8: false
#          use-black: false
#          use-mypy: false
#          use-isort: false
      - name: Pylint run
        if: matrix.os == 'ubuntu-latest'
        uses: ricardochaves/python-lint@v1.3.0
        with:
          python-root-list: "symphony tests"
          use-pylint: true
          use-pycodestyle: false
          use-flake8: false
          use-black: false
          use-mypy: false
          use-isort: false

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results-${{ matrix.os }}
          path: test-results/junit.xml
        if: ${{ always() }}

      - name: Upload test coverage
        uses: actions/upload-artifact@v2
        with:
          name: pytest-coverage-${{ matrix.os }}
          path: htmlcov
        if: ${{ always() }}
