name: build

on:
  push:
    branches: [ "2.0" ]
  pull_request:
    branches: [ "2.0" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pypoetry/virtualenvs
          - os: macos-latest
            path: ~/Library/Caches/pypoetry/virtualenvs
          - os: windows-latest
            path: ~\AppData\Local\pypoetry\Cache\virtualenvs

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        run: pip install poetry

      - name: Cache poetry
        uses: actions/cache@v2
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: poetry install

      - name: Run tests with coverage
        run: poetry run pytest

#      - name: Download workflow artifact for pylint diff
#        if: matrix.os == 'ubuntu-latest'
#        uses: dawidd6/action-download-artifact@v2.12.0
#        with:
#          workflow: build.yml
#          workflow_conclusion: success
#          name: .pylint.d
#          path: ~/.pylint.d

#      - name: Run Pylint
#        if: matrix.os == 'ubuntu-latest'
#        run: poetry run pylint symphony tests

      - name: Run Pylint
        if: matrix.os == 'ubuntu-latest'
        uses: github/super-linter@v3.14.0
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON_PYLINT: true
          DEFAULT_BRANCH: "2.0"
          FILTER_REGEX_INCLUDE: .*symphony/.*
          OUTPUT_FOLDER: pylint-results
          LINTER_RULES_PATH: /
          PYTHON_PYLINT_CONFIG_FILE: .pylintrc

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results-${{ matrix.os }}
          path: test-results/junit.xml
        if: ${{ always() }}

      - name: Upload test coverage
        uses: actions/upload-artifact@v2
        with:
          name: pytest-coverage-${{ matrix.os }}
          path: htmlcov
        if: ${{ always() }}

#      - name: Upload pylint results
#        if: matrix.os == 'ubuntu-latest'
#        uses: actions/upload-artifact@v2
#        with:
#          name: .pylint.d
#          path: ~/.pylint.d
      - name: Upload pylint results
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: pylint-results-${{ matrix.os }}
          path: pylint-results